### PR TITLE
use archive[JavaInfo].runtime_output_jars

### PR DESCRIPTION
**Pull request by ittaiz**
@iirina the travis build here should fail and with your change should pass

### CODE REVIEW

**Comment by ittaiz** [comment]
@iirina

**Comment by iirina** [comment]
Thanks for the repro @ittaiz! I'll give it a try today and let you know how it went.

**Comment by iirina** [comment]
I only managed to start the tests now, I'll report the results tomorrow.

**Comment by iirina** [comment]
There are still some failing tests (e.g. `test_scala_import_expect_failure_on_missing_direct_deps_warn_mode`). I have to investigate this in more detail to see what's going on exactly. @ittaiz can you open an issue and link this PR?

**Comment by ittaiz** [comment]
Sure. An issue in bazel about runtime_output_jars not containing all the
expected jars?

**Comment by iirina** [comment]
@ittaiz yup sounds good, thank you!

**Comment by ittaiz** [comment]
done
https://github.com/bazelbuild/bazel/issues/8916

**Comment by ittaiz** [comment]
@iirina can we close this PR? right now it's somewhat of white noise

**Comment by iirina** [comment]
Yup, thanks.

**Comment by ittaiz** [comment]
I don’t remember. I’ll check and update you.

**Comment by ittaiz** [comment]
`//test:JunitMixedSeparateTarget_test_runner `. And in general the PR still links to the failing builds (both buildkite and travis). For example https://buildkite.com/bazel/rules-scala-scala/builds/980
Thanks!

**Comment by iirina** [comment]
@ittaiz Thanks! I should've checked the buildkite logs :) I did the same change you did in this PR (but in `scala/private/rules/scala_junit_test.bzl` since the code moved) and ran the test with bazel built at https://github.com/bazelbuild/bazel/commit/acdd3654e70af880f412c2bc5c8a9b5c4f477bf2 and the test passed \o/ The I ran all tests under `//test` and they all passed. It looks like it's a safe change now. The fix will land in bazel 1.1.

**Pull request closed without merging**
