### PR TITLE
use tools in run_shell

### LINKED ISSUE #596: Found tool(s) 'external/bazel_tools/tools/zip/zipper/zipper' in inputs.
```
external/io_bazel_rules_scala/scala/private/rule_impls.bzl", line 106, in _build_nosrc_jar
                ctx.actions.run_shell(inputs = inputs, outputs = outs, com..., <2 more arguments>)
Found tool(s) 'external/bazel_tools/tools/zip/zipper/zipper' in inputs. A tool is 
an input with executable=True set. All tools should be passed using the 
'tools' argument instead of 'inputs' in order to make their runfiles available 
to the action. This safety check will not be performed once the action is 
modified to take a 'tools' argument. To temporarily disable this check, set 
--incompatible_no_support_tools_in_action_inputs=false.
```

### PR DESCRIPTION
**Pull request by johnynek**
closes #596 

The linting seems to be floating on head I guess and no longer works for me.

We really need to nail down all external dependencies onto shas so we don't break CI randomly....

ptal @ittaiz

### CODE REVIEW

**Comment by johnynek** [comment]
I guess this also failed due to #600 

All deprecations all the time! Welcome to bazel!

**Comment by ittaiz** [comment]
Can you rebase on top of master?

**Comment by johnynek** [comment]
merged master.

**Comment by johnynek** [comment]
This is failing the lint check since the linter is broken. I guess there is no burning need to merge the current PR.

I'll wait and see if @andyscott has time to fix this up.

**Comment by ittaiz** [comment]
👍🏽

**Comment by ittaiz** [comment]
@johnynek looks like the breakage of lint now is actual. Can you run fix and push again? If you're too tired on this let me know

**Comment by johnynek** [comment]
@ittaiz here is the output I get running `lint.sh` on this branch:

https://gist.github.com/johnynek/c76dd39f1f51ae02638fd4db327f160c

Something has changed and there is a massive list of problems and it won't automatically fix it. I have not started looking through the 900 lines of output yet.

I did file this ticket #602 that running the lint.sh is no longer working.

Can you verify try running lint.sh on this branch and see if somehow this is local state?

cc @andyscott

**Comment by johnynek** [comment]
PS: I'm not crazy about formatting tooling that fails. If it is easy, great, if it is a hassle, those that care about it should make it easy and we should disable until then.

**Comment by ittaiz** [comment]
obsolete

**Pull request closed without merging**
