### PR TITLE
ScalaPB deps toolchain

### PR DESCRIPTION
**Pull request by liucijus**
Refactors scalapb toolchain to use DepsInfo providers to pass required dependencies. Part of #940

### CODE REVIEW

**Comment by ittaiz** [comment]
is this a breaking change?

**Comment by liucijus** [comment]
> is this a breaking change?

If I'm not missing anything, it should not be breaking (it refactors private attributes)

**Review by ittaiz — APPROVED** [review]

**Comment by ittaiz** [comment]
Build is broken

**Comment by liucijus** [comment]
@ianoc-stripe do you remember why [this](https://github.com/bazelbuild/rules_scala/blob/master/test/shell/test_deps.sh#L19) test is needed? Toolchains automatically include host paltform as an [execution platform](https://docs.bazel.build/versions/master/toolchains.html#toolchain-resolution). Is it a problem?

**Comment by liucijus** [comment]
Moving this PR to draft, due to:
Generators like [`@io_bazel_rules_scala//src/scala/scripts:scalapb_worker`](https://github.com/bazelbuild/rules_scala/blob/e612d3e670ef1a8363488ab043139512c517750e/src/scala/scripts/BUILD#L53) depend on the same libs that come via proto toolchain, which ends up in a cyclic resolution [here](https://github.com/bazelbuild/rules_scala/blob/master/scala_proto/scala_proto_toolchain.bzl#L32). I assume we  need to introduce another toolchain for proto deps, so generators can get deps before their are resolved from the proto toolchain.

**Comment by liucijus** [comment]
We may need to upgrade to at least Bazel 3.5.0 address toolchain limitations (#801 ). @ittaiz WDYT?

**Comment by ittaiz** [comment]
I can live with that if I understand the exact value gain and reason.
Value gain is #751 ?
If so why do we need 3.5.0 for exactly? What does toolchain limitations mean? Best if we can have a text and a link to bazel issue + PR

**Comment by liucijus** [comment]
Limitation is that with a current state of toolchains, all deps are added as host: https://github.com/bazelbuild/rules_scala/issues/797. It's address with an ongoing work on execution transitions (https://groups.google.com/g/bazel-discuss/c/vXrG6uFL5V8/m/RjK8_chaEgAJ). 
Even with 3.5.0 it is problematic as it requires flag `--incompatible_override_toolchain_transition` to be used. It would be reasonable to wait until the full support in later Bazel versions, but then we need an alternative way to address #751

**Comment by ianoc-stripe** [comment]
@liucijus I might be missing something but how does the deps coming via the bind or the toolchain effect #751 ?

**Comment by liucijus** [comment]
> @liucijus I might be missing something but how does the deps coming via the bind or the toolchain effect #751 ?

Bind should be ok, but toolchain deps will be added as host deps, no?

**Comment by ianoc-stripe** [comment]
@liucijus having them in the bind keeps it off the host deps. But the issues around having deps in the toolchain or not is unconnected with #751 as far as i know. You can add/change the deps via the bind (indeed we bind these against local java_libraries iirc to setup the deps we use locally).  It would be nice to move the deps on the toolchain since it seems like thats how it should be done, but afaik it won't solve any of our other issues today

**Comment by liucijus** [comment]
this PR is ready to be merged

**Pull request merged**
