### PR TITLE
Use jar from java runtime and not local_jdk

### PR DESCRIPTION
**Pull request by ittaiz**
Work around and somewhat prepare for resolution of
https://github.com/bazelbuild/bazel/issues/6955

### CODE REVIEW

**Comment by ittaiz** [comment]
@anchlovi would love your thoughts here

**Comment by ittaiz** [comment]
@beala-stripe if you're using scala_binary/repl/test (as opposed to java_binary) you can take a look at this solution. It requires copying the stub to your workspace.
I think I'll improve this and expose it as an http_archive.
This is better than the workaround of local_jdk IMHO

**Comment by beala-stripe** [comment]
Thanks! I'll try to find some time to test this out later.

**Comment by ittaiz** [comment]
@johnynek this is ready apart from the fact that I'd like to serve the stub from a public place and use http_archive

**Comment by ittaiz** [comment]
@johnynek any thoughts or objections?

**Comment by johnynek** [comment]
Thanks @ittaiz

**Comment by ittaiz** [comment]
Thank you!

**Pull request merged**
