### PR TITLE
Create CODEOWNERS

### PR DESCRIPTION
**Pull request by dslomov**

### CODE REVIEW

**Comment by dslomov** [comment]
Hey folks please lmk and any of you want to be the admin @ittaiz @johnynek @dinowernli

**Comment by johnynek** [comment]
@dslomov what does “admin” mean in this context? Is this file purely documentation or does it effect any system?

**Comment by dslomov** [comment]
> @dslomov what does “admin” mean in this context? Is this file purely documentation or does it effect any system?

Admins can add collaborators to the repository.

**Comment by johnynek** [comment]
I'd like to be an admin (I imagine @ittaiz would like to as well).

**Comment by ittaiz** [comment]
Indeed, thanks! (Back from a 10 day vacation without reception 🙂)

**Pull request merged**
