### PR TITLE
Capture javac args in a @argfile

### PR DESCRIPTION
**Pull request by softprops**
This should fix issue #151

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by softprops** [comment]
I think the cla I had signed was for one email address but these commits are associated with another. I've added a cla agreement for my the email address associated with the commits in this pull

**Comment by johnynek** [comment]
can you say "I signed it" or something, and see if the bot picks it up?

**Comment by softprops** [comment]
@johnynek having my co-pilot  ( @jrodbeta ) verify his cla. I think its a combination of both of our agreements. I'll check in after

**Comment by softprops** [comment]
I signed it

**Comment by jrodbeta** [comment]
I signed it

**Comment by johnynek** [comment]
"CLAs are signed, but unable to verify author consent"

So maybe all the authors need to have signed since there are multiple ones?

**Comment by softprops** [comment]
I think we're just trying to figure out how to trip the pr bot now

**Comment by johnynek** [comment]
cool, okay since it looks like I am just supposed to verify these multi-person commits, it looks like it is legit, and it looks like the build passes, so I'll merge.

Thanks for the contribution, @softprops and @jrodbeta

**Comment by softprops** [comment]
thanks man

**Comment by jrodbeta** [comment]
Thanks @johnynek  I'm wondering if it's because of company email.  I'll get the company CLA done for next time.

**Comment by ittaiz** [comment]
as an FYI from my experiments with the bot it seems like the primary email needs to sign (Be it private or corporate)

**Comment by ittaiz** [comment]
no test here :( @johnynek I'd suggest that at least for bug fixes targeted like this we mandate a test. WDYT?

**Comment by softprops** [comment]
I'm happy to follow up with some unit tests.

**Comment by ittaiz** [comment]
I would appreciate that

**Comment by johnynek** [comment]
@ittaiz It would be nice to have a test that failed before and now works. We are testing this code in the existing java-scala mixed targets, which is why I accepted it without a stronger test.

I kind of bias towards being pretty certain it is not worse, especially for newer contributors. But, yes, ideally we could be stronger and be sure that it is even better than it was before.

**Comment by ittaiz** [comment]
I understand. The problem I'm worried about is the fear of change or its
reckless friend the regression. We will eventually refactor and/or add
features there and we want that agility.

**Pull request merged**
