### PR TITLE
remove spotify from adopters

### PR DESCRIPTION
**Pull request by ittaiz**
### Description
remove spotify from adopters

They looked at Bazel but didn't adopt

### Motivation
Up-to-date adopters list

### CODE REVIEW

**Comment by ittaiz** [comment]
@nevillelyh I'm not mistaken, right?

**Comment by mandrean** [comment]
@ittaiz There are 2-3 teams using it and a few more are considering it. But most of the company will remain on whatever is "default" for a particular language, like e.g. Maven, for the foreseeable future.

**Comment by mandrean** [comment]
And the only reason why I found this PR is because I'm working on an internal project and needed to pin `rules_scala` to the latest commit hash 😂

**Comment by ittaiz** [comment]
Thanks! I met with @nevillelyh in NYC and understood no one uses it.
Happy to hear some teams are getting value from it.
Re-adding you.

**Comment by nevillelyh** [comment]
@ittaiz thanks. You’re correct that we (the scala infra team) don’t use it but there are a few downstream (feature teams) that do.

**Pull request merged**
