### PR TITLE
Bump Bazel to v2.0.0

### PR DESCRIPTION
**Pull request by chenrui333**
### Description

Bump Bazel to the latest `v2.0.0`.

relates to bazelbuild/bazel#10131

### CODE REVIEW

**Comment by ittaiz** [comment]
Thanks! You’ve moved to it already?
Let’s see if the tests pass...

**Comment by chenrui333** [comment]
Yeah, I am trying to get all our dependencies aligned with the new version before pulling the switch, I might do it after the new year though. :)

**Comment by ittaiz** [comment]
I suggest you take a look at #865 ? It’s a big change and I suggest you see meetup works well with it

**Comment by chenrui333** [comment]
Cool, I will take a look!

**Pull request merged**
