### PR TITLE
use worker proto file instead of precompiled java

### PR DESCRIPTION
**Pull request by andyscott**
### Description

Use the worker proto file instead of the pregenerated java.

### Motivation

It seems a bit cleaner to me to depend on the proto instead of the prebuilt Java. The proto file is also easier to update. The only drawback is there's an overhead to bootstrapping protobuf, but pretty much every Bazel project does that anyway, so the cost is shared.

### CODE REVIEW

**Comment by ittaiz** [comment]
Interesting. Definitely more manageable but TBH I'm somewhat concerned about this change due to the perf implications.
I've heard many related complaints about the protoc dependency and it's overhead internally and externally (https://github.com/bazelbuild/rules_scala/issues/769, https://bazelbuild.slack.com/archives/CDCKJ2KFZ/p1579853509003000).
@simuons @sha1n wdyt?

**Comment by simuons** [comment]
@ittaiz well if you ask me this looks like a reasonable thing to do in current state of rules_scala. The protoc compilation "issue" exists even without this change. Once thats issue will be resolved code in this PR would change as well.

**Comment by ittaiz** [comment]
My main concern is that it will make it even harder to change our direction. If we want to change it then maybe we shouldn't continue to advance in the other direction.
Another smaller concern is the concrete increase in build times since we see internally and externally many re-compilations of proto outputs.

**Comment by ittaiz** [comment]
I’m merging though there is a chance we’ll need to revert it if we get too many backlashes.

**Pull request merged**
