### PR TITLE
Rename set to depset

### PR DESCRIPTION
**Pull request by vladmos**

### CODE REVIEW

**Comment by ittaiz** [comment]
Thanks!

**Comment by johnynek** [comment]
Wait, this was red in CI, right?

**Comment by vladmos** [comment]
It looks like flakiness or misconfiguration: test_run.sh: line 210: bazel: command not found

I don't see how this change can break anything, `set` and `depset` are completely equivalent and `depset` was introduced months ago.

**Comment by ittaiz** [comment]
This was red in CI because Bazel removed the ability to test against HEAD.
That's also why master is broken.
Or will send a PR later to susped HEAD testing from travis.
We're waiting for
https://github.com/bazelbuild/continuous-integration/issues/95

**Comment by ittaiz** [comment]
@johnynek @or-shachar noticed that they returned the binaries to the pipeline so I manually triggered the build and master is green again :)

**Pull request merged**
