### PR TITLE
[WIP] Add detection for unused classpath entries as part of strict mode

### PR DESCRIPTION
**Pull request by jjudd**
Based on what I read in #235, I hacked together a quick `unused_deps` implementation that is currently bundled together with `strict_java_deps`. 

This is a work in progress. I would like to get people's feedback on this before continuing.

### CODE REVIEW

**Comment by jjudd** [comment]
This should be it's own flag. I bundled it with `strict_java_deps` for the sake of speed in building a prototype.

**Comment by jjudd** [comment]
Wanted to provide an update here: we're still working on this and should hopefully have something within the next couple weeks. 

We found an issue with macros and `classpath-shrinker`, which I filed an issue about: https://github.com/scalacenter/classpath-shrinker/issues/4

I like their suggestion of adding a whitelist for deps that are actually used, but the plugin marks as unused. That way `unused_deps` doesn't become totally blocked on bugs in the classpath shrinking mechanism.

We're moving into using our internal version of this to remove unused deps from our build files in combination with ibazel. If that goes well, we will polish it up and update this PR.

**Comment by ittaiz** [comment]
Sounds good!
Sorry I haven’t had the chance to go over the code.
How do you think of handling the whitelist?

**Comment by johnynek** [comment]
really excited about this! Thank you!

**Comment by jjudd** [comment]
I was planning on adding an attribute to the scala rules for the whitelist. The attribute lists the deps that should not be marked as unused.

I'm open to other ways of solving this. Ideally I'd be able to tag deps in the actual deps list, but I'm I don't think Bazel supports that.

**Comment by ittaiz** [comment]
Does the bug mean you remove “macro code”?
Meaning if you were to automatically whitelist code that was tagged as
having macro would that solve the problem?
Because we have scala_macro_library (or similar name) and scala_import will
soon also have this distinction (since it will use ijars for non macro code)

**Comment by jjudd** [comment]
I'm not totally certain if that macro classpath bug happens for all macros or just some. I was able to repro with those two jars, but there are others that I can't repro the problem with.

Automatically whitelisting scala_macro_library and scala_import would likely fix the issue. It may whitelist too many things, though. 

As I work on optimizing our internal build files over the next few weeks, I'll see what happens and keep people updated.

**Comment by ittaiz** [comment]
Sounds good.
To be clear- I don’t think we need to whitelist all of scala_import but we
want to turn on ijars for scala_import by default and have the ability to
turn them off. For those where we turn them off we can take that as a cue
for macro existence and whitelist them

**Comment by ittaiz** [comment]
Closing this since we have unused deps. Thanks.

**Pull request closed without merging**
