### PR TITLE
Fixed protobuf URL in README

### PR DESCRIPTION
**Pull request by pawelaw**
### Description

Fixed protobuf URL in README

### Motivation

With the last protobuf version update in the README, the URL needs to include the 'v' prefix before the version.

### CODE REVIEW

**Comment by ittaiz** [comment]
What about the strip prefix part? Also CLA is needed

**Comment by pawelaw** [comment]
@googlebot I signed it!

**Comment by pawelaw** [comment]
> What about the strip prefix part? Also CLA is needed

The strip_prefix value is relevant only to the content of the archive - inside the archive there is a top level directory protobuf-3.11.3 (without the 'v'). Seems like there's some inconsistency. Nevertheless, the download URL requires 'v' prefix.

**Comment by gergelyfabian** [comment]
Thanks @pawelaw for fixing the bug I introduced... :)

**Pull request merged**
