### PR TITLE
Update bazel to 0.16.1

### PR DESCRIPTION
**Pull request by ittaiz**

### CODE REVIEW

**Comment by ittaiz** [comment]
Needed by #583 cc @jjudd

**Comment by jjudd** [comment]
Awesome. Thanks for upgrading this.

**Comment by ittaiz** [comment]
Sure thing. It even seems it will pass. Unfortunately we needed to disable
our own strict checks for bazel issues due to much noise

**Comment by johnynek** [comment]
Can you update the shas in the README.md to help people see which shas work with which versions?

**Comment by ittaiz** [comment]
Not sure I understand which shas you’re referring to

**Comment by johnynek** [comment]
https://github.com/bazelbuild/rules_scala#bazel-compatible-versions

I think we should set the 14.1 version to the current sha. If we aren’t testing it any longer we aren’t sure it works.

**Comment by ittaiz** [comment]
@johnynek PTAL

**Comment by ittaiz** [comment]
Oscar,
I’m planning of merging tomorrow morning if I don’t hear any objections now
that I’ve updated the readme.

**Pull request merged**
