### PR TITLE
Use --compression in _build_deployable

### PR DESCRIPTION
**Pull request by prebeta**
For the feature request in: https://github.com/bazelbuild/rules_scala/issues/598

### CODE REVIEW

**Comment by ittaiz** [comment]
For our internal rule (which does an Uber jar but with some other stuff
like filtering and shading) it was a substantial change.
Given this doesn’t have a test should we add a small comment saying why and
that it’s not covered?
Not a must but might be helpful if someone touches the area

**Comment by prebeta** [comment]
Using compression reduced the size of our fat jar from 1.5GB to 500MB. We have not seen any significant regressions in behavior during compilation or in production. It also looks like we use compression by default in our internal JarCreator: https://github.com/bazelbuild/rules_scala/blob/master/src/java/io/bazel/rulesscala/jar/JarCreator.java#L281

@ittaiz We already have a comment with a pointer to the flags available in SingleJar, so I'm not sure what additional information would be useful in this case. If you have a specific suggestion for content, I can add that into the PR.

**Comment by ittaiz** [comment]
I’m really sorry @prebeta but you’ll have to rebase and push

**Comment by prebeta** [comment]
@ittaiz sounds good. I've rebased and added a comment as well.

**Pull request merged**
