### PR TITLE
Use singlejar to build deployable scala binaries

### PR DESCRIPTION
**Pull request by azymnis**
Attempts to address issue #261

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by ittaiz** [comment]
Bazel build test/... breaks

**Comment by azymnis** [comment]
@ittaiz this is the error

```
Traceback (most recent call last):
	File "/home/travis/build/bazelbuild/rules_scala/test/BUILD", line 199
		scala_repl(name = 'ReplWithSources')
	File "/home/travis/build/bazelbuild/rules_scala/scala/scala.bzl", line 654, in _scala_repl_impl
		_scala_binary_common(ctx, cjars, transitive_rjars, jars.tra..., ...)
	File "/home/travis/build/bazelbuild/rules_scala/scala/scala.bzl", line 580, in _scala_binary_common
		_build_deployable(ctx, list(rjars))
	File "/home/travis/build/bazelbuild/rules_scala/scala/scala.bzl", line 316, in _build_deployable
		args.extend(["--main_class", ctx.attr.main_c...])
	File "/home/travis/build/bazelbuild/rules_scala/scala/scala.bzl", line 316, in args.extend
		ctx.attr.main_class
No attribute 'main_class' in attr. Make sure you declared a rule attribute with this name.
```

I'll fix this now

**Comment by ittaiz** [comment]
Wdyt about adding a test for this issue?
Just in case someone will later want to move to the "new" singlejar for some other reason and it won't support this.

**Comment by johnynek** [comment]
looks like we need `--normalize` to fix that issue:
https://github.com/bazelbuild/bazel/blob/master/src/java_tools/singlejar/java/com/google/devtools/build/singlejar/SingleJar.java#L77

**Comment by johnynek** [comment]
+1 it would be great to have a test so we don't regress on this.

**Comment by azymnis** [comment]
@johnynek @ittaiz I'll try to add a test. I think this would require checking in a couple of jars that contains manifest info for services, packaging them into a scala binary, and then checking the generated jar's manifest info

I'll fix the normalize issue now

**Comment by johnynek** [comment]
this is great @azymnis .

Will merge when linux 0.5.3 goes green (our HEAD testing is broken at the moment sadly...)

**Comment by johnynek** [comment]
test this please

(message for cibot)

**Comment by azymnis** [comment]
@johnynek hmm weird, looks like this is hanging: https://travis-ci.org/bazelbuild/rules_scala/builds/270975861?utm_source=github_status&utm_medium=notification

**Comment by johnynek** [comment]
restarted the osx 0.5.3. build. Let's see if it goes green. If so, I will merge.

Thanks, @azymnis

**Comment by johnynek** [comment]
okay, the non-head builds are green. Merging.

Thanks so much @azymnis ! welcome to the team!

**Comment by azymnis** [comment]
@johnynek @ittaiz you're welcome. I may have another coming up for adding [scalapb](https://github.com/scalapb/ScalaPB) rules

**Comment by johnynek** [comment]
Hell yeah. We are starting to use proto as well so we are going to need the same. Someone at Stripe may already be working on this. I will try to get a PR up soon so we can collaborate.

**Comment by ittaiz** [comment]
:) we're also starting to use protos so we'll have a need for this later on

**Pull request merged**
