### PR TITLE
forcing utf-8 encoding with javac

### PR DESCRIPTION
**Pull request by or-shachar**
`java_library` compiles UTF-8 files without special configurations.
On systems where UTF-8 is not the default encoding, `scala_library` fails when compiling java code with UTF-8 characters, showing error: 
```
error: unmappable character for encoding ASCII
```
As part of the effort to be compliant with java_library - I suggest we do the same.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by ittaiz** [comment]
test this please (cibot)

**Comment by ittaiz** [comment]
test this please (cibot)

**Comment by ittaiz** [comment]
test this please (cibot)

**Pull request merged**
