### PR TITLE
Reporter tests

### PR DESCRIPTION
**Pull request by andrefmrocha**
### Description
Added a series of tests for the different reporters used throughout different scala versions.

I have also taken the liberty to uncomment the tests for the `DiagnosticsReporter`, since the toolchain flag allows for the usage of this without a development version of bazel (I think leaving them uncommented beforehand was a mistake). Do let me know what you think of that :smile: 

### Motivation
Related to #1161 . This guarantees that different changes made to how the build is interpreted do not break error reporting.

I don't think this should close the issue, since it doesn't yet address problems in error reporting on scala 2.11 when using the `DiagnosticsReporter`.

### CODE REVIEW

**Comment by andrefmrocha** [comment]
@googlebot I signed it!

**Comment by andrefmrocha** [comment]
I've also managed to fix the error exit code on 2.11 . Is it fine for me to use this pull request to close everything?

**Comment by liucijus** [comment]
please move **failing** tests under `test_expect_failure`, any other tests should go under `test`

**Comment by liucijus** [comment]
> I've also managed to fix the error exit code on 2.11 . Is it fine for me to use this pull request to close everything?

If this fix does not overlap/depend on this PR, I prefer a smaller separate PR.

**Comment by liucijus** [comment]
> please move **failing** tests under `test_expect_failure`, any other tests should go under `test`

Because these test are version based, maybe they can be moved to a package under version tests, and be excluded in version test case to avoid failure, WDYT @andrefmrocha?

**Comment by andrefmrocha** [comment]
I've gone ahead and made the changes in question. I've decided to keep the package outside since the `version_specific_tests_dir` but still inside the `test_version` since, even though I do believe there is a flag so that a specific package is not built with commands such as `bazel build //...`, I think this would make the tests quite more complicated to read.

Do let me know what you think!

**Review by liucijus — APPROVED** [review]
LGTM!

**Review by ittaiz — APPROVED** [review]
Thanks!

**Pull request merged**
