### PR TITLE
Improve scala_config() documentation in README.md

### PR DESCRIPTION
**Pull request by kolotyluk**
### Description
Per https://github.com/bazelbuild/rules_scala/issues/1490 improve README.md

### Motivation
As a documentation wonk, I like documentation to minimize mistakes, and following the original documentation led to some copy/paste mistakes that had to be cleared up in the issues. 

When I figure out how to support Scala 3, I will update the documentation again with a better explanation.

### CODE REVIEW

**Comment by kolotyluk** [comment]
All I changed was `README.md` so I don't understand why this is failing...

**Comment by kolotyluk** [comment]
CLA has been signed now...

**Comment by liucijus** [comment]
@googlebot I signed it!

**Comment by liucijus** [comment]
> CLA has been signed now...

Still failing, @kolotyluk could you check if you have signed with the same email as your commits were made?

**Comment by kolotyluk** [comment]
Google Identity Management is broken. There is no possible way in their UI to correct the information. I will have to contact them.

**Comment by kolotyluk** [comment]
I spent a fair bit of time with Google One support trying to sort out the problem... Next, follow up with more specialized people at Google...

**Comment by kolotyluk** [comment]
It seems that Google CLA does not work on Firefox... I have resubmitted via Chrome... Hopefully this works...

**Comment by kolotyluk** [comment]
Updated CLA with my GitHub identity.

**Review by liucijus — APPROVED** [review]
Thanks, @kolotyluk!

**Review by simuons — APPROVED** [review]

**Pull request merged**
