### PR TITLE
Move declare_executable to phase file

### PR DESCRIPTION
**Pull request by borkaehw**
### Description

Move `declare_executable` to the phase file. There is no need for importing from other file.

### Motivation

Clean-up work of phase PR.

### CODE REVIEW

**Comment by borkaehw** [comment]
`is_windows` is also used by `write_executable` in `rule_impls.bzl`, but I will move that soon.

**Comment by ittaiz** [comment]
The force push is because you rebased with the https?
Also, why not move the declare executable now? Because you’re trying to keep it small?

**Comment by borkaehw** [comment]
> The force push is because you rebased with the https?

Yes, otherwise CI failed.

> why not move the declare executable now?

Not sure what do you mean here. It's a PR to move `declare_executable`. Do I miss something? Or do you mean `write_executable`?

**Comment by ittaiz** [comment]
Yes, that’s what I meant. Thanks.
I want to suggest I’ll take the move pieces from rule_impls/common to phases.
Will make it easier for me to know where everything is.
Also this way I’ll send one PR to keep our commit history small and since you have an idea on what the changes look like it should be easier for you to review.
Most importantly is that I won’t be doing any semantic changes just moving code around.
I hope to send the PR today.
Ok?

**Comment by borkaehw** [comment]
Sounds good to me. I will focus on `phase_scalafmt` and other stuff. Is there anything on the list that I can help?

**Pull request merged**
