### PR TITLE
Create Governance.md

### PR DESCRIPTION
**Pull request by ittaiz**
### Description
Add document to explain how this repo is governed.

### Motivation
clarify how development is done, welcome new contributors and maintainers.

This is following a 2 months period of the [google docs version](https://docs.google.com/document/d/1VgqFvXLvt1t0EIoUxYTwnyKgTiE8S5miD7nHwtbywRc/edit) of this waiting for inputs and after announcements in gitter and slack I'm moving this forward and merging it

### CODE REVIEW

**Comment by hicksjoseph** [comment]
LGTM on the content. You may want to review in the future for grammar and punctuation.

**Comment by liucijus** [comment]
@ittaiz maybe it's not too late for grammar and punctuation reviews?

**Comment by ittaiz** [comment]
We can but given the fact that it's been sitting for a few good months in the open it's a bit annoying.
Maybe we should merge as is and then do a round of fixes?

**Comment by hicksjoseph** [comment]
Sounds good. Let's merge and then review for grammar and punctuation.

**Pull request merged**
