### PR TITLE
Allow injecting versions and shas for scala extra jars

### PR DESCRIPTION
**Pull request by exchgr**
re: https://github.com/bazelbuild/rules_scala/issues/619#issuecomment-424927132

### CODE REVIEW

**Comment by johnynek** [comment]
This looks good to me, but I think you need to sign the google CLA.

**Comment by exchgr** [comment]
Thanks! I'm working on getting on my company's CLA

**Comment by johnynek** [comment]
looks like the lint test failed. I'm going to disable that since the fixup isn't working for us at the moment.

Thanks for the PR.

**Comment by exchgr** [comment]
Thank you!

**Pull request merged**
