### PR TITLE
Specify the statsfile output in the rule output struct

### PR DESCRIPTION
**Pull request by andyscott**
Looks like I forgot to add the statsfile to the output struct needed by downstream aspects.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by ittaiz** [comment]
Test this please (ci bot)

**Comment by ittaiz** [comment]
@andyscott I can merge this but are you sure you don't want this also in binaries? you've added this to the _lib outputs

**Comment by andyscott** [comment]
@ittaiz Fixed to specify the statsfile for scala binaries too.

**Comment by johnynek** [comment]
test this please

**Comment by johnynek** [comment]
@andyscott that a look at this: https://github.com/tweag/rules_haskell/pull/121 there they access a command line option to control if they are in profiling or coverage mode. It might be useful to copy the same approach for doing more invasive instrumentation.

**Pull request merged**
