### PR TITLE
Add compatibility test for v1.2.0

### LINKED ISSUE #880: Upgrade to be compatible with Bazel 1.2.0
As Bazel [v1.2.0](https://github.com/bazelbuild/bazel/releases/tag/1.2.0) is out, we should upgrade the build config to check on the compatibility.

### PR DESCRIPTION
**Pull request by chenrui333**
### Description

Fixes #880

Update build config for Bazel 1.1.0 and Bazel 1.2.0

### Motivation

Keep up to date with the latest Bazel and meetup is actually actively using this lib.

### CODE REVIEW

**Comment by chenrui333** [comment]
Right now we are actually using Bazel 1.1.0 in production, so I am confident with Bazel 1.1.0 upgrade. 

But it would be nice to also introduce the compatibility test for Bazel 1.2.0 as well. :)

**Comment by chenrui333** [comment]
Also relates to https://github.com/meetup/rules_openapi/pull/22

**Comment by ittaiz** [comment]
Thanks!
I’d rather we update 1.0.0 to 1.2.0 since our past experience tells us that having too many versions on Travis kills our ability to merge code in easily.

**Comment by chenrui333** [comment]
@ittaiz Sounds totally reasonable. Let me update it.

**Comment by ittaiz** [comment]
build failed. Can you PTAL?

**Comment by ittaiz** [comment]
We can have two PRs by the way. We can have to upgrade to 1.1.0 and then a followup one to replace it with 1.2.0
If we do that I'd appreciate the diffs to be as small as possible (should be close to replacing 1.0.0 to 1.1.0 and so on)

**Comment by chenrui333** [comment]
Sure. Sounds like a better idea.

**Comment by chenrui333** [comment]
Breakdown the upgrade steps in new PRs, closing this one for now :)

**Pull request closed without merging**
