### PR TITLE
Fix build jacoco scripts

### PR DESCRIPTION
**Pull request by BillyAutrey**
### Description
Fixes for #1277.  Updated jacoco build script and test script to use specific tags and new test locations.  

### Motivation
I attempted to run these scripts, and ran into several issues.  After a lot of troubleshooting and debugging, I figured out the root causes and a few potential fixes.  Decided to submit a PR with these fixes, in case it helps anyone else attempting the same thing.

### CODE REVIEW

**Comment by BillyAutrey** [comment]
@googlebot I signed it!

**Comment by liucijus** [comment]
Thanks @BillyAutrey! 

@gergelyfabian your review would be very valuable here

**Comment by gergelyfabian** [comment]
It looks all good to me (assuming it also works, I did not have a chance to
check that). This is a beautiful example of why open source is nice, you
once contribute and then someone else fixes your code (when it stops
working due to other changes).

Great thanks @BillyAutrey <https://github.com/BillyAutrey>!

Vaidas Pilkauskas ***@***.***> ezt írta (időpont: 2021. júl.
28., Sze 13:54):

**Comment by BillyAutrey** [comment]
I ran all of the scripts, and they worked for me locally.  The test script works as well.  I do invite others to dry run these scripts, however.  I'd be happy to correct them if any of my assumptions were wrong.

**Review by liucijus — APPROVED** [review]

**Comment by liucijus** [comment]
I've tried the test script - it finished successfully

**Review by simuons — APPROVED** [review]

**Pull request merged**
