### PR TITLE
Specs2 filtering of JUnit descriptions

### PR DESCRIPTION
**Pull request by hmemcpy**
This PR augments the fix introduced in #759. The previous PR introduced a bug with incorrectly flattening JUnit descriptions - their original hashCode value was lost, and this caused failed tests to appear as succeeded in the bazel runner.

This PR replaces the flattening logic by having Specs2 itself create the Descriptions, keeping their original hashCode values.

Adding some tests to make sure only valid results appear in the XML.

@ittaiz

### CODE REVIEW

**Comment by hmemcpy** [comment]
Ugh, this needs a bit more work.

**Comment by hmemcpy** [comment]
Hmm, I don't know why two of these seem to fail... They pass on my machine too, any ideas @ittaiz @johnynek?

**Comment by ittaiz** [comment]
Not sure exactly what's going on:
```
Test "scala_specs2_only_failed_test_shows_in_the_xml" failed  (3 sec) 
The command "if [[ "${TRAVIS_OS_NAME}" == "windows" ]]; then
```

**Comment by hmemcpy** [comment]
OMG finally! Turns out you need to set `set +e` in your test if you're expecting test failures. Everything should pass now. @ittaiz please take a look.

**Pull request merged**
