### PR TITLE
Unconditionally use java_executable_runfiles path.

### PR DESCRIPTION
**Pull request by lberki**
This is now in Bazel in the latest release, so it works this way.

### CODE REVIEW

**Comment by lberki** [comment]
ping @iirina @travisbrown

**Comment by ittaiz** [comment]
@lberki thanks! 
@johnynek with respect to your plans of having master be up to date and keep version branches. Do you want to to bump the minimum version to 0.11.1? (I think this is what's effectively happening here)

**Comment by johnynek** [comment]
I’m fine with that, and we can merge the other PR into the bazel_0_10 branch for people on earlier versions.

We should fix the .travis.yml file so travis can go green @lberki

**Comment by ittaiz** [comment]
Sounds good

**Comment by johnynek** [comment]
@lberki it does not look like you fixed the travis build so now our master is broken.

We use travis because we have a number of negative tests that we have not yet put into bazel, i.e. tests where we expect targets to fail.

**Comment by lberki** [comment]
@johnynek I misunderstood you -- I thought Travis was already red and you are recommending an independent change to fix that :( Let me just try my hand at it...

**Pull request merged**
