### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by systemlogic**

### CODE REVIEW

**Comment by johnynek** [comment]
Thanks for the PR! Can you add a bit more information so we can document in this PR our source. Are you on a team that is using Bazel with scale at IBM? Can you describe the project? Is there are more specific URL for the project we can add than ibm.com?

Thanks again!

**Comment by johnynek** [comment]
Any update here? I'd love to merge this, but would like to have a bit more information and better link.

**Comment by systemlogic** [comment]
My Squad lead is not commenting on this PR, You can close it.

**Comment by johnynek** [comment]
If anything changes and you have more details to share later please feel free to open another PR!

**Pull request closed without merging**
