### PR TITLE
Sync Scala 2.12 with master

### PR DESCRIPTION
**Pull request by gkk-stripe**
Follow up to #358 that had master as target by mistake.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by ittaiz** [comment]
@gkk-stripe can you resolve conflicts?

**Comment by gkk-stripe** [comment]
it says:
> This branch has no conflicts with the base branch

**Comment by ittaiz** [comment]
Where?
I see

> This branch cannot be rebased due to conflicts
> Rebasing the commits of this branch on top of the base branch cannot be performed automatically due to conflicts encountered while reapplying the individual commits from the head branch.

**Comment by gkossakowski** [comment]
It was in github ui, I think github got confused by merge+revert in master. I merged master into 2.12 again using:
```
git merge -s ours origin/master
```
This should give us an effect of ignoring the faulty merge+revert in master.

**Comment by ittaiz** [comment]
i somehow managed to get this to work via cmdline :)

**Comment by ittaiz** [comment]
@gkossakowski I did another merge and push directly to the branch so FYI

**Comment by ittaiz** [comment]
@gkossakowski reverted it, for some reason it broke the build

**Pull request merged**
