### PR TITLE
Scala 2.12 support

### PR DESCRIPTION
**Pull request by hmemcpy**
This subsumes and closes #407.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by hmemcpy** [comment]
@ittaiz please review. This is a result of applying a diff between `origin/scala2_12` and a new branch (generated with `git diff master origin/scala2_12`)

**Comment by ittaiz** [comment]
Test this please

**Comment by johnynek** [comment]
I don't want to merge 2.12 into master until we have a way to select the version in the scala_toolchain. Can we instead update the 2.12 branch here so users can select their scala version by choosing a branch in git?

**Comment by hmemcpy** [comment]
Right, I'm sorry, I pushed to the wrong head... I'll coordinate with @ittaiz and send the changes on top of the 2.12 branch.

**Pull request closed without merging**
