### PR TITLE
fixes after scalapb upgrade

### PR DESCRIPTION
**Pull request by darl**
### Description
Build fixes for scala 2.12 and strict_deps enabled

### Motivation
Build failures in my current project after last PR (#1026)

### CODE REVIEW

**Comment by darl** [comment]
I think it's a problem:

CI fails with `dependency_tracking_method = 'default'` and without explicit protobuf dependency;

my local build fails with `dependency_tracking_method = 'high-level'` and with explicit dependency from master.

**Comment by ittaiz** [comment]
1. Sorry for the delay. Corona times are wrecking a havoc in my availability.
2. I think that the best thing to do is to revert your change and then push a new commit that only adds the failure that you're seeing locally to CI. Then we can try and devise a solution.
I'll try to do it now.

cc @Jamie5 I have a hunch that somewhere in the flag changes we lost some of the e2e tests we used to have

**Comment by ittaiz** [comment]
btw, worst case I think we'll be able to add the problematic dep to the ignore targets of `scalapb_generator_lib`.
Let's hope we wont' reach this.

**Comment by ittaiz** [comment]
Also right [now](https://github.com/bazelbuild/rules_scala/blob/9c84950f5d6e8f3cb9fdac06d9a9fdaff37ae4ad/scala/scala_toolchain.bzl#L26) `dependency_tracking_method='default'` means `dependency_tracking_method='high-level'`.
It would really help to get a repro or even just your full setup.
What toolchain are you using (one of the default ones or a custom ones), what scala_repositories and which target fails (I'm assuming it's the same one that's failing right now but would love to make sure).

**Comment by ittaiz** [comment]
btw, it would also help to see the exact failure

**Comment by ittaiz** [comment]
Closing in favor of #1030 which has a workaround for both issues.
Feel free to reopen if you have strong objections.

**Comment by ittaiz** [comment]
btw, this isn't time critical or anything, right? 
Asking since I'd like to give Jamie time to review #1030 and we don't have anything newer than the scalapb upgrade so I'm guessing you can wait but would still like to verify

**Comment by darl** [comment]
I can wait for #1030 to be merged

**Pull request closed without merging**
