### PR TITLE
Prepare for --incompatible_use_toolchain_providers_in_java_common

### LINKED ISSUE #712: Prepare for --incompatible_use_toolchain_providers_in_java_common
context: bazelbuild/bazel#7186

The breaking change is expected to happen in Bazel 0.25, and requires updates to rules_scala.

### PR DESCRIPTION
**Pull request by cushon**
see https://github.com/bazelbuild/bazel/issues/7186

Fixes #712

### CODE REVIEW

**Comment by cushon** [comment]
The recommended migration strategy is incompatible with Bazel 0.22 (that's why the CI is failing).

How do you want to proceed?

**Comment by cushon** [comment]
>  this needs 0.23 and not even 0.22, right?

Yep, the first version this will work with is 0.23.

**Comment by ittaiz** [comment]
We have another PR which will land in the next 2-3 days which updates the
travis to 0.23.
Is it ok if we wait with this PR until then? Would rather not have
conflicts there it's really big.

**Comment by cushon** [comment]
> We have another PR which will land in the next 2-3 days which updates the travis to 0.23. Is it ok if we wait with this PR until then?

I think that sounds fine. The breaking change should be releases in 0.25, which won't happen until April.

**Comment by beala-stripe** [comment]
IIUC this bumps the minimum version to 0.23? Would it be possible to merge the code coverage PR first (https://github.com/bazelbuild/rules_scala/pull/692) so we can use it at Stripe without having to upgrade? We just spent a fair bit of time upgrading to 0.22.

**Comment by johnynek** [comment]
can you merge master?

**Comment by ianoc** [comment]
@cushon master has been updated to require 0.23 so if you re-merge in master this should be able to go green

**Comment by cushon** [comment]
It looks like the CI is green now (thanks!), is this blocked on anything else?

**Comment by johnynek** [comment]
thank you!

**Pull request merged**
