### PR TITLE
extra javac opts should override default ones

### PR DESCRIPTION
**Pull request by thomasbao12**
### Description

Fixes https://github.com/bazelbuild/rules_scala/issues/1550

Currently the default javac flags will be appended last, overriding the manual ones.

### CODE REVIEW

**Comment by liucijus** [comment]
@thomasbao12 could you add a test to prevent regressions?

**Comment by thomasbao12** [comment]
@liucijus I added a test and verified it fails on master https://github.com/bazelbuild/rules_scala/pull/1615.

I tried to follow the pattern established in other javac tests.

One issue though is I assume the default java toolchain sets a -target flag.  

3 potential options:
0. merge as is
1. I could rename the test to clarify that I actually am only testing that I want to be able to override the java target version.  This is actually the behavior I want to fix.
2. I could try a more elaborate unit-test that verifies that two javac flags exist, one from the default toolchain and one from javacopts and that the javacopt one is ordered after the default toolchain.

I'm okay with 0 & 1.  I worry 2 is not worth doing and overly specific.

**Comment by liucijus** [comment]
> 3 potential options:
> 
>     0. merge as is
> 
>     1. I could rename the test to clarify that I actually am only testing that I want to be able to override the java target version.  This is actually the behavior I want to fix.
> 
>     2. I could try a more elaborate unit-test that verifies that two javac flags exist, one from the default toolchain and one from javacopts and that the javacopt one is ordered after the default toolchain.
> 

@thomasbao12 if I haven't missed anything, option 0 seems the best to me - it communicates  your need plus the name implies generic expectation

**Review by liucijus — APPROVED** [review]
Thanks, @thomasbao12!

**Comment by thomasbao12** [comment]
@liucijus Can you merge?

**Review by simuons — APPROVED** [review]

**Pull request merged**
