### PR TITLE
Move examples build to bk

### PR DESCRIPTION
**Pull request by liucijus**
Move examples testing to BuildKite

### CODE REVIEW

**Review by or-shachar — APPROVED** [review]
LGTM!
(just curiosity question - what's the difference in durations between travis and bk?)

**Review by ittaiz — APPROVED** [review]
Looks good. Do you know why the checks are still pending?

**Comment by liucijus** [comment]
> Looks good. Do you know why the checks are still pending?

@ittaiz where do you see pending checks?

**Comment by liucijus** [comment]
> LGTM!
> (just curiosity question - what's the difference in durations between travis and bk?)

Roughly BuildKite 1.34 vs Travis 2.30 min

**Comment by ittaiz** [comment]
on my phone it showed the checks as pending

**Pull request merged**
