### PR TITLE
Fix edge case, you can export some targets but not depend on those. M…

### PR DESCRIPTION
**Pull request by ianoc-stripe**
…ostly not an issue, but building the library target should also build the children

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by johnynek** [comment]
Can we add a test that exposes the issue? But if you're swamped this fix seems like the right thing.

**Comment by ianoc-stripe** [comment]
I'll try come up with a test, i think it needs to be a failing build one. (If something else depends on this target i think it winds up getting the exports built).

**Comment by ianoc-stripe** [comment]
Added a first commit, to get us a failing test, then will re-apply the fix

**Comment by johnynek** [comment]
Thanks a ton for adding the test.

**Pull request merged**
