### PR TITLE
Sync Scala 2.12 with master

### PR DESCRIPTION
**Pull request by gkk-stripe**
One straightforward merge conflict.
Let's see if it still passes CI.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by ittaiz** [comment]
test this please

**Comment by ittaiz** [comment]
@nadavwe FYI. I guess I can cut you our rules_scala flavor with 2.12 tomorrow if this is merged today

**Comment by gkk-stripe** [comment]
Yes, let’s merge!

**Comment by gkossakowski** [comment]
Oooops. I've made a mistake of targetting master. We need to revert this.

**Comment by gkossakowski** [comment]
PR coming

**Pull request merged**
