### PR TITLE
wip - generate service provider configuration for `scala_library` targets

### PR DESCRIPTION
**Pull request by ity**
Add a `services` attribute to `scala_library` for this additional information. See #696 for details.

### CODE REVIEW

**Comment by ittaiz** [comment]
Can you please rebase on top of master? You have conflicts and the diff with test_rules_scala.sh is confusing

**Comment by ity** [comment]
> Can you please rebase on top of master? You have conflicts and the diff with test_rules_scala.sh is confusing

just did, thanks for taking a look!

**Comment by johnynek** [comment]
@ity good to see you!

I wonder, would it be possible for this to be a separate rule that just builds a jar that has this file? Then it could be added as a runtime dependency or any java or scala library?

In that way, it wouldn't be coupled to the scala library at all.

How does that sound?

**Comment by ity** [comment]
> @ity good to see you!
> 
> I wonder, would it be possible for this to be a separate rule that just builds a jar that has this file? Then it could be added as a runtime dependency or any java or scala library?
> 
> In that way, it wouldn't be coupled to the scala library at all.
> 
> How does that sound?

@johnynek thanks :)

And yes, making it a separate rule makes sense to me! I can edit and send an update in the same PR.

**Comment by ity** [comment]
Realistically, I might not get to this in the next 2 weeks or so - so if anyone wants to take a stab at this in the meantime, feel free. Otherwise I will get to this as soon as I can.

**Comment by ittaiz** [comment]
@ity do you think you'll get to it or I'll close this?

**Comment by liucijus** [comment]
closing as stale, feel free to reopen

**Pull request closed without merging**
