### PR TITLE
[WIP] Handle a unused_dependency_checker_ignored_targets

### PR DESCRIPTION
**Pull request by Jamie5**
### Description
WIP, just here for the CI

### Motivation
WIP

### CODE REVIEW

**Comment by Jamie5** [comment]
@ittaiz I suspect this is an issue with the high-level mode, because looking the source I don't see references to xml. And it seems this does work with ast mode. So once we switch transitive to use ast instead of high-level by default (and change the tests to all use ast instead of high-level), this should be solved.

**Comment by ittaiz** [comment]
SGTM,
Do we want to have an issue open for removing this instance of `unused_dependency_checker_ignored_targets` and link it to the discussion of making `high-level` the default?

**Comment by Jamie5** [comment]
I added a mention in the first post of https://github.com/bazelbuild/rules_scala/issues/867 (which contains the other TODOs as well), is that sufficient?

**Comment by ittaiz** [comment]
Indeed. Can we close this PR for now?

**Pull request closed without merging**
