### PR TITLE
add recommended setup for intellij .bazelproject to new scripts folder

### PR DESCRIPTION
**Pull request by natansil**
to help contributers who work on Intellij

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by johnynek** [comment]
This looks good to me. What is it about Scrooge that doesn't work? I wonder if there is something we can fix.

**Comment by ittaiz** [comment]
We don't really know. On one of the IntelliJ issues we opened @chaoren said
it's not supported

**Comment by chaoren** [comment]
> On one of the IntelliJ issues we opened @chaoren said it's not supported

By that I mean I didn't get to add any special support for it. It it's just a bunch of libraries (jars not files) attached to scala rules (library, binary, test, etc), then it should work out of the box.

**Comment by johnynek** [comment]
I'm happy to merge this, but I don't use intellij so I can't really evaluate it very well. I'll leave to @ittaiz to merge.

**Pull request merged**
