### PR TITLE
I think this should be tag, not commit, since the value is a tag

### PR DESCRIPTION
**Pull request by petemounce**

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by petemounce** [comment]
`I signed it!`

This time, I've changed my github.com account to use my improbable.io account as my primary - we've signed it as a company. So, it would be great if the bot could be improved to account for when a contributor has more than one email and matching against at least one having signed the CLA.

**Comment by johnynek** [comment]
Thanks!

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Pull request merged**
