### PR TITLE
Support data files in jmh benchmarks

### PR DESCRIPTION
**Pull request by tferi-da**

### CODE REVIEW

**Comment by tferi-da** [comment]
@johnynek feel free to make a copy of this PR, as I'm waiting for our legal department to sign off my contribution - it might be faster if you merge a copy.

**Comment by tferi-da** [comment]
I signed it!

**Comment by tferi-da** [comment]
I signed it!

**Comment by johnynek** [comment]
Thanks again!

**Comment by tferi-da** [comment]
Thank you for the quick turnaround :)

**Pull request merged**
