### PR TITLE
Use worker proto from @bazel_tools

### PR DESCRIPTION
**Pull request by illicitonion**
This avoids needing to vendor our own copy.

### CODE REVIEW

**Comment by liucijus** [comment]
> I guess we could maybe merge this when 5.x lands?

This would force everyone to upgrade to Bazel 5, I guess we will have to wait a bit more.

**Comment by liucijus** [comment]
@illicitonion we are on Bazel 6, would you be interested to rebase on your changes on current master?

**Comment by illicitonion** [comment]
Rebased - thanks so much!

**Review by liucijus — APPROVED** [review]
Thanks,  @illicitonion!

**Review by simuons — APPROVED** [review]

**Pull request merged**
