### PR TITLE
scala 2.12.10 is default version, closes #703

### LINKED ISSUE #703: Default Scala version should be 2.12 (instead of 2.11)
Currently the default version is 2.11.12:

https://github.com/bazelbuild/rules_scala/blob/ad41d0ca4f49a712956f5f9ba608cc1d8d47f40f/scala/scala_cross_version.bzl#L25

But according to [JB 2018 survey](https://www.jetbrains.com/research/devecosystem-2018/scala/) only 30% used 2.11, while 64% used 2.12

I think it's time to change the default...

### PR DESCRIPTION
**Pull request by ittaiz**
### Description
scala 2.12.10 is default version

### Motivation
#703

### CODE REVIEW

**Comment by smparkes** [comment]
Not sure if it's overloading too much, but could make the jump to `2.12.11` while we're here?
```
        "2.12.11": {
            "shas": {
                "scala_compiler": "e901937dbeeae1715b231a7cfcd547a10d5bbf0dfb9d52d2886eae18b4d62ab6",
                "scala_library": "dbfe77a3fc7a16c0c7cb6cb2b91fecec5438f2803112a744cb1b187926a138be",
                "scala_reflect": "5f9e156aeba45ef2c4d24b303405db259082739015190b3b334811843bd90d6a",
            },
        },
```

**Comment by ittaiz** [comment]
@smparkes test coverage on fails when I apply your change. I'm reverting but I'd welcome a passing PR to upgrade to 2.12.11

**Comment by smparkes** [comment]
@ittaiz ack

We manually configure 2.12.11 but we haven't run all the tests. Our code is probably less sensitive. I'll see if I can carve out some time.

**Comment by ittaiz** [comment]
arghh. Even after the revert it fails. I hope it's a travis problem. Though not really sure why only on that test. It's late enough for me to not think straight. I'll try to rerun in the morning and we'll see

**Comment by ittaiz** [comment]
ok, it seems the coverage failure is legit. 
I looked into the passing commit and the travis build didn't run there so that's probably why it passed.

**Comment by ittaiz** [comment]
I've updated the golden coverage file and so the test passes of course.
It sounds reasonable that if we upgraded the libraries then the coverage file might have changed format. @gergelyfabian @smparkes would still love your 2c about this if it indeed sounds reasonable since I'm always ware when changing tests

**Comment by gergelyfabian** [comment]
I think there is some strange change with coverage on this branch.

Steps:

1. Generate coverage data:
`bazel coverage  --extra_toolchains="//scala:code_coverage_toolchain" //test/coverage/...`
2. Generated coverage report:
`genhtml -o ${destdir} --ignore-errors source bazel-out/k8-fastbuild/testlogs/test/coverage/test-all/coverage.dat`

The report on master and on 2_12_default is significantly different.
E.g. in coverage/D1.scala.gcov.html all the function lines seem to be covered on master, while on 2_12_default only the first line is shown as covered.
On master, line coverage is 91.1%, while on 2_12_default it's 85.7%.

I checked this, because I got suspicious when I saw the differences in the expected lcov file (removing mentions of `veryLongFunctionNameIsHereAaaaaaaaa`).

**Comment by ittaiz** [comment]
:( always be cautious when changing tests...

@gergelyfabian thanks for taking the time!
How do you think we should proceed?

**Comment by gergelyfabian** [comment]
Results of `lcov --list bazel-out/k8-fastbuild/testlogs/test/coverage/test-all/coverage.dat` on master:

```
Reading tracefile bazel-out/k8-fastbuild/testlogs/test/coverage/test-all/coverage.dat
                   |Lines       |Functions  |Branches    
Filename           |Rate     Num|Rate    Num|Rate     Num
=========================================================
[test/coverage/]
A1.scala           |66.7%      3|75.0%     4|    -      0
A2.scala           | 100%      2|75.0%     4|    -      0
B1.scala           |50.0%      2|50.0%     4|    -      0
B2.java            |25.0%      4|33.3%     3|    -      0
C2.scala           | 100%      2| 100%     4|    -      0
D1.scala           | 100%     36|98.6%    70|    -      0
TestAll.scala      | 100%      7| 100%     9|    -      0
=========================================================
             Total:|91.1%     56|92.9%    98|    -      0
```

On 2_12_default:

```
Reading tracefile bazel-out/k8-fastbuild/testlogs/test/coverage/test-all/coverage.dat
                   |Lines       |Functions  |Branches    
Filename           |Rate     Num|Rate    Num|Rate     Num
=========================================================
[test/coverage/]
A1.scala           | 100%      4|75.0%     4|    -      0
A2.scala           | 100%      3|75.0%     4|    -      0
B1.scala           |66.7%      3|50.0%     4|    -      0
B2.java            |25.0%      4|33.3%     3|    -      0
C2.scala           | 100%      3| 100%     4|    -      0
D1.scala           | 100%      4|75.0%     4|    -      0
TestAll.scala      | 100%      7| 100%     1|    -      0
=========================================================
             Total:|85.7%     28|70.8%    24|    -      0
```
```

**Comment by gergelyfabian** [comment]
I'm not an expert on lcov data generation, but maybe there is a difference how Scala 2.12 classes are generated / instrumented. I believe this would need some debugging, because evidently lines which are executed are not detected by coverage.

**Comment by ittaiz** [comment]
Coming to think about it I’m not sure we should block the merge because of this.
I think we found a problem with coverage on 2.12 which we should open an issue for and then hopefully @gergelyfabian can iterate on it while master is on 2.12, right?
If we merge this it doesn’t worsen the state of those using rules scala with coverage on 2.12

**Pull request merged**
