### PR TITLE
Fixup some of the tests

### PR DESCRIPTION
**Pull request by sdtwigg**
In test_run.sh:
* Move test_build_identical to the end (as per #217), add comment
* Move all the binary runs together, sort them

In test/BUILD:
* Add missing test binary runs (and sort them)
  Now is same as in test_run.sh

### CODE REVIEW

**Comment by johnynek** [comment]
👍

**Comment by johnynek** [comment]
I'm okay with my commits (the merge conflict resolve) being included cibot.

**Comment by ittaiz** [comment]
Why do we need to add all the binaries in the test/BUILD? What confidence does this bring us?

**Comment by sdtwigg** [comment]
They were originally added to ensure there was no discrepancy between blaze
test using the binary and blaze run due to runfiles weirdness.

At this point though (with runfiles setup being sorted by the launcher), I
put them in test/BUILD because I'm more likely to do a quick blaze test
test/... than run test_run.sh when in the middle of changes.

**Comment by ittaiz** [comment]
I see. Then maybe we should cut down the number of happy cases we have in
test_run.sh? We obviously need a few for confidence and regression of
"bazel run" but I definitely agree the feedback cycle of "bazel test
//test/..." is much faster

**Comment by sdtwigg** [comment]
Sounds reasonable.

**Comment by johnynek** [comment]
Thinking more about this, I'm not sure it does matter where the build is identical test goes in the order. Yes it removes everything but it also rebuilds everything.

Why does it matter where it goes in order?

**Comment by ittaiz** [comment]
I think you're right. We can also in the build logs that the tests which
follow take a short time so it shouldn't be an issue.

**Comment by sdtwigg** [comment]
I re-reviewed. For some reason, I earlier thought that the identical test was only checking some of the jars under test/..., but it seems to be checking all of them.

This is far less useful now. It is maybe nice to do the identical test at the end because it is the longest so if you break a test after it in test_run, you aren't waiting as long.

**Comment by johnynek** [comment]
Yeah, that's true. For that reason running last is a good idea.

**Comment by ittaiz** [comment]
I suggest, rebase, green build and let's merge

**Comment by ittaiz** [comment]
@sdtwigg do you want to resolve the conflicts or do you have too much going on? I can do it if you're too busy. Obviously #227 is order of magnitudes more important :)

**Comment by sdtwigg** [comment]
Just got back from a small vacation. Will try to hit both over the weekend (as catching up on my directwork related tasks must take priority :) )

**Comment by ittaiz** [comment]
:)
Awesome! This is starting to be a blocker for us since we need *runtime*
location expansion and that is only supported (partially) in java_test.
This means I need to switch test running to be a macro (scala library and
java_test). If there is anything I can do to help please let me know.

**Comment by ittaiz** [comment]
closed in favor of #398 thanks @sdtwigg!

**Pull request closed without merging**
