### PR TITLE
fixed travis for HEAD

### PR DESCRIPTION
**Pull request by or-shachar**
travis stopped working for HEAD. 
This script should fix it.

Warning: the regex is hideous , but that's the only thing that captured all cases (RC/linux/darwin)

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by ittaiz** [comment]
test this please

**Comment by or-shachar** [comment]
still needs work on mac version :-(

**Comment by or-shachar** [comment]
trying again

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Pull request merged**
