### PR TITLE
Delete dead code from ProtoReporter

### PR DESCRIPTION
**Pull request by cocreature**
### Description

Deletes a bunch of dead code.

### Motivation

It’s not used anywhere.

### CODE REVIEW

**Comment by simuons** [comment]
@andrefmrocha you have added this code as part of https://github.com/bazelbuild/rules_scala/pull/1068 but PR https://github.com/bazelbuild/bazel/pull/11766 for which this code was added is stuck.
Do we still need to keep this code around? Are there any plans to progress with https://github.com/bazelbuild/bazel/pull/11766?

**Comment by andrefmrocha** [comment]
> @andrefmrocha you have added this code as part of #1068 but PR [bazelbuild/bazel#11766](https://github.com/bazelbuild/bazel/pull/11766) for which this code was added is stuck.
> Do we still need to keep this code around? Are there any plans to progress with [bazelbuild/bazel#11766](https://github.com/bazelbuild/bazel/pull/11766)?

Unfortunately I've had very little feedback on bazelbuild/bazel#11766, even after various attempts to reach out. So I think it's okay to remove it.

**Comment by andrefmrocha** [comment]
However, the ProtoReporter's output as a whole is already being used in [bazel-bsp](https://github.com/JetBrains/bazel-bsp), so I hope we can maintain that

**Comment by cocreature** [comment]
> However, the ProtoReporter's output as a whole is already being used in [bazel-bsp](https://github.com/JetBrains/bazel-bsp), so I hope we can maintain that

absolutely, I’m not trying to get rid of the proto output. Just of code that isn’t contributing to producing the output.

**Review by simuons — APPROVED** [review]
Thanks @andrefmrocha, I just wanted to know there is nothing planned for this code in near future.

@cocreature thanks for PR. LGTM.

**Review by liucijus — APPROVED** [review]

**Pull request merged**
