### PR TITLE
Update to Scala 2.12.6

### PR DESCRIPTION
**Pull request by jmendiara**
Update scala `2.12.3` -> `2.12.6` in the `scala2_12` branch

### CODE REVIEW

**Comment by johnynek** [comment]
looks like the intellij tests are not passing. Do they fail normally on 2.12? I didn't think so, cc @ittaiz

**Comment by jmendiara** [comment]
mmm... Running on a MAC, bazel 0.14, after removing `--experimental_local_disk_cache`  from `bazel.rc` ...

```sh
$ ./test_intellij_aspect.sh
running test test_intellij_aspect local master
 Test "test_intellij_aspect local master" successful (282 sec)
```

But `test_rules_scala.sh` and `test_reproducibility` fails. Ask for logs if you want

```sh
$ xcodebuild -version
Xcode 9.4.1
Build version 9F2000

$ bazel version
Build label: 0.14.0-homebrew
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jun 1 14:26:58 2018 (1527863218)
Build timestamp: 1527863218
Build timestamp as int: 1527863218
```

PD: The README says we cannot pass tests on MAC, and refers to a set of merged/closed issues. Is this correct?

**Comment by ittaiz** [comment]
I don’t know...
Haven’t had a chance to take a closer look.

Re the comment I think it’s stale. Would love a PR :)

**Comment by johnynek** [comment]
Can you merge master and try again?

We have made a number of changes. The intellij test was broken for a day or two.

**Comment by jmendiara** [comment]
This PR, derived from `scala2_12` branch, has diverged a lot from master and the merge is kind of painful. Maybe is worth waiting for #544?

**Pull request closed without merging**
