### PR TITLE
Fix deployable JARs created by Scala rules.

### PR DESCRIPTION
**Pull request by devnev**
"Deployable" Jars, as created by the java_binary rule, are Jars with all runtime dependencies included. These are usable as standalone Jars that can be deployed onto servers and such. The reason why we need these for Scala binaries and libraries is as a bandaid fix for Java/Scala interop in Bazel. The Java ecosystem of rules is closed: AFAICT, only known-good rules (cc_library, java_library, java_import, ...) can be used as dependencies of java libraries and binaries. To work around this, the scala_export_to_java macro injects scala into the java ecosystem via "precompiled" jars in the java_imports rule. However, this rule does not pick up transitive runtime dependencies of the imported Jars, so when using these Jars in java_tests, the tests fail because they do not have access to the runtime dependencies of the imported Scala Jar. To make these imports work, the imported Jar must therefore be one that includes the full runtime dependencies in the Jar itself, which is what correctly-built "deploy" Jars provide.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by dinowernli** [comment]
This looks legit to me, but please wait for one of @johnynek to ack.

**Comment by johnynek** [comment]
This looks good, and fixes #20 #25 . I do have anxiety that these jars may be quite big, and have a lot of duplication, so actually solving #57 is still worth doing if that is your goal.

Also note, due to #53 , on OSX, jar is not respecting timestamps, so each run invalidates the cache, which is a real bummer. A fix for that will have fix this code as well.

**Comment by johnynek** [comment]
@devnev thanks for your contribution!

**Comment by johnynek** [comment]
@devnev we are having some issues with this PR. It significantly increases the build time for all our targets.

We need to find a way to deal with this. Is it the case that you only want the `scala_to_java_export` to work correctly? If so, we can fix that to actually compute the real deps and not generate the deploy jar for all libraries. It seems that in bazel, deploy jars are only implicit outputs of `java_binary` so maybe we should follow that approach and not build them for `scala_library`.

**Comment by johnynek** [comment]
also, see issue bazelbuild/bazel#970

**Pull request merged**
