### PR TITLE
Upgrade bazel travis to 0.12.0

### PR DESCRIPTION
**Pull request by ittaiz**
Hopefully this supersedes #481 (cc @pauldraper)
Like discussed on the ticket I've changed the assertion (due to the naming it was pointless to loosen the assertion so I changed it a bit).

### CODE REVIEW

**Comment by ittaiz** [comment]
also apologies for this dragging on for some time

**Comment by ittaiz** [comment]
@johnynek it seems that we have a problem with 0.13.0 and protobuf repository.
```
The value 'REPOSITORY_NAME' has been removed in favor of 'repository_name()', please use the latter (https://docs.bazel.build/versions/master/skylark/lib/native.html#repository_name). You can temporarily allow the old name by using --incompatiblePackageNameIsAFunction=false
```
https://travis-ci.org/bazelbuild/rules_scala/jobs/380855273
On master of protobuf this is still the deprecated form so we should probably open an issue to them.
I want to see that it works with 0.12.0 and then I'll open the relevant issue

**Comment by johnynek** [comment]
huh, are we using an old sha?

Pretty frustrating if google can't even keep up with the deprecation cycle they create.

**Comment by ittaiz** [comment]
We're using an older sha but even on master it isn't fixed.
yeah, it is a bit frustrating.
I think I'll mention it (in a good way) in the issue.

**Comment by ittaiz** [comment]
@buchgr the buildkite failed very strangely. Any chance you can take a look?
Funny enough the files changed don't relate to the bazel build on buildkite...

**Comment by buchgr** [comment]
Sorry I missed this. Is there still a problem?

**Pull request merged**
