### PR TITLE
Split sh test

### PR DESCRIPTION
**Pull request by borkaehw**
### Description
Split up integration tests in `test_rules_scala.sh` into separate files. 

### Motivation
This is based on the discussion https://github.com/bazelbuild/rules_scala/issues/824. We haven't had an agreement on what the integration tests will look like eventually, but this PR will help to ease the pain to run all the tests at once when developing locally.

## Verify Tests Still Fail
- [x] test_build_event_protocol.sh
- [x] test_compilation.sh
- [x] test_deps.sh

(X) test_javac_jvm_flags.sh
    - javac_jvm_flags_are_expanded
    - javac_jvm_flags_via_javacopts_are_expanded
- [x] test_junit.sh
- [x] test_misc.sh
- [x] test_scala_binary.sh
- [x] test_scala_classpath.sh

(X) test_scala_import_source_jar.sh
    - test_scala_import_source_jar_should_not_be_fetched_when_env_bazel_jvm_fetch_sources_is_set_to_non_true
- [x] test_scala_jvm_flags.sh
- [x] test_scala_library.sh

(X) test_scala_library_jar.sh
    - scala_library_jar_without_srcs_must_fail_on_mismatching_resource_strip_prefix
- [x] test_scala_specs2.sh

(X) test_scalac_jvm_flags.sh
    - test_scalac_jvm_flags_are_expanded
(X) test_toolchain.sh
    - java_toolchain_javacopts_are_used
- [x] test_unused_dependency.sh

## Tests With Issues
- [ ] test_javac_jvm_flags.sh:  javac_jvm_flags_are_expanded
    - Problem: Changing failing message doesn't fail the test.
    - Status: **Not fixed**
- [ ] test_javac_jvm_flags.sh: javac_jvm_flags_via_javacopts_are_expanded
    - Problem: Changing failing message doesn't fail the test.
    - Status: **Not fixed**
- [x] test_misc.sh: test_repl
    - Problem: It relies on `scala_repl` to be built, previously was done by `$runner bazel build test/...`
    - Status: Fixed
 - [ ] test_scala_import_source_jar.sh: test_scala_import_source_jar_should_not_be_fetched_when_env_bazel_jvm_fetch_sources_is_set_to_non_true
    - Problem: It actually gets error `Command 'test_scala_import_fetch_sources' not found. Try 'bazel help'.`, but the message was silence by `$runner`.
    - Status: **Not fixed**
- [ ] test_scala_import_source_jar.sh: scala_library_jar_without_srcs_must_fail_on_mismatching_resource_strip_prefix
    - Problem: `no such package 'test_expect_failure/wrong_resource_strip_prefix'`.
    - Status: **Not fixed**
- [ ] test_scalac_jvm_flags.sh: test_scalac_jvm_flags_are_expanded
    - Problem: Changing failing message doesn't fail the test.
    - Status: **Not fixed**
- [ ] test_toolchain.sh: java_toolchain_javacopts_are_used
    - Problem: Changing failing message doesn't fail the test.
    - Status: **Not fixed**

### CODE REVIEW

**Comment by borkaehw** [comment]
@long-stripe Thanks! This PR is ready for review and being merged.

**Comment by ittaiz** [comment]
@borkaehw thanks for this. This is a very large diff so I'll need your help with it.
A few questions:
1. Can you confirm you only cut/pasted parts into separate files? If not I need to go over the entire diff
2. Have you verified tests still fail? I'd love you to verify at least one test case in each file can still fail reasonably. One of the biggest issues we had with bash was that tests stopped failing and we found about it only months after it happened
3. Did you have any need for new common code due to splitting out code from a shared file? If so can you explain what you did?
4. Some of the current tests aren't standalone and rely on existing state happening. I guess the main sh file passes because you've kept the order of calls the same as before if we inline everything. Did you run every file on its own? If they don't pass we need to think what to do with them (at the minimum document dependencies)

Thanks again

**Comment by borkaehw** [comment]
Thanks @ittaiz 
1. I can confirm I only cut and pasted.
2. It reminds me that some tests take 0 second to complete. It might because we are not even testing them? I can see at least `javac_jvm_flags_are_expanded` might be broken since changing the message didn't cause a failure (and it takes 0 second). I will do more testing.
3. Are you referring `test_helper.sh`? Some functions are shared across test files, I think it's good to have a shared file to avoid duplicate code. Though we already have `test_runner.sh` as shared file, I am not opposed to merge them.
4. Not only the main sh file passes, each sh file passes if you run them alone. I did group tests in order based on their name, but contiguous tests can be split into different files. I didn't know tests aren't standalone, but it went well that all tests still pass.

I suppose tests should behave the same. If the some tests rely on existing state, I might need people's help to identify them. If some tests stop failing and it's an existing issue, I would like to fix them in different PR so that we keep this PR in scope "Split sh test". Thanks.

**Comment by ittaiz** [comment]
> It reminds me that some tests take 0 second to complete. It might because we are not even testing them? I can see at least javac_jvm_flags_are_expanded might be broken since changing the message didn't cause a failure (and it takes 0 second). I will do more testing
0 seconds to complete might be because they're really fast (they depend on workspace state from previous tests) so not sure it means enough but the message might. When you change it on master what happens? In general I think all of our tests are in good shape now but I might be wrong of course.
3. Re `test_helper.sh`- I meant whether you had such a file :) Didn't see it was added in this big diff... Merging it can be well but can wait for next PR. You should probably verify that all tests that use methods from it can fail.

I think in general I'd love to understand the following high level:
1. Which, if any, specific test files break when run separately (after bazel clean)?
2. Make sure that tests still fail (I'd guess a single case in each file is good indication).

**Comment by borkaehw** [comment]
> When you change it on master what happens?

For tests using `action_should_fail_with_message` are not working on `master`. It includes `scalac_jvm_flags_are_expanded`, `javac_jvm_flags_are_expanded`, `javac_jvm_flags_via_javacopts_are_expanded`, and `java_toolchain_javacopts_are_used`. I haven't tested others.

3. Yeah, there is a new file `test/shell/test_helper.sh` where I put helper functions in it.

> Which, if any, specific test files break when run separately (after bazel clean)?

All separate test files pass after `bazel clean`. On the opposite, I see `test_scala_import_expect_failure_on_missing_direct_deps_warn_mode` is failing without `bazel clean`. 

I will do a more comprehensive testing about "tests still fail".

**Comment by ittaiz** [comment]
Thanks, I appreciate it.
I think these difficulties speak loudly on the costs of maintaining bash
testing infra...

**Comment by long-stripe** [comment]
I've never written bash I didn't come to regret later 😂.

**Comment by borkaehw** [comment]
I have done a comprehensive testing. The complete report is on the PR description. I can confirm the tests listed are also not working on `master`. It would be nice to address those issues after this PR.

**Comment by borkaehw** [comment]
Thanks, happy to help! I will create corresponding issues followed by PR fixes later.

**Comment by ittaiz** [comment]
Thanks! Looking forward to the follow up issues

**Comment by borkaehw** [comment]
We can track the follow-up issues here: https://github.com/bazelbuild/rules_scala/issues/855 https://github.com/bazelbuild/rules_scala/issues/856 https://github.com/bazelbuild/rules_scala/issues/857

**Pull request merged**
