### PR TITLE
Add support for Scala 3.2

### LINKED ISSUE #1464: Add support for Scala 3.2
Add support for Scala 3.2

The current stable version of Scala is 3.2.1: https://github.com/lampepfl/dotty/releases/tag/3.2.1

### PR DESCRIPTION
**Pull request by meisam**
### Description
Add support of Scala 3.2

- Add the build and repository definitions for Scala 3.2.1
- Add an extra set of tests for Scala 3.2.1

### Motivation
- To stay as close as possible to the head of Scala.
-  To make new features in Scala 3.2 available to developers.

Fixes #1464

### CODE REVIEW

**Review by liucijus — APPROVED** [review]

**Comment by liucijus** [comment]
Thanks, @meisam!

**Comment by meisam** [comment]
I verified the issue in #1408 is fixed in Scala 3.2.

**Comment by anagrius** [comment]
We would appreciate this getting merged! Thanks @meisam

**Comment by meisam** [comment]
> We would appreciate this getting merged! Thanks @meisam

Waiting for @simuons to approve the PR.

**Comment by pshemass** [comment]
@simuons could you approve this?

**Review by simuons — APPROVED** [review]
Thanks! And sorry for delay.

**Comment by fabianhjr** [comment]
Are the changes on third_party/repositories/scala_3_2.bzl made manually or is there an automated script to update the dependencies?

**Comment by liucijus** [comment]
> Are the changes on third_party/repositories/scala_3_2.bzl made manually or is there an automated script to update the dependencies?

@fabianhjr Yes, they are manual changes. If, as a user, you need specific versions, you can define them using [custom toolchain](https://github.com/bazelbuild/rules_scala/blob/master/docs/scala_toolchain.md).

**Pull request merged**
