### PR TITLE
Remove the deprecated attribute proto_source_root.

### PR DESCRIPTION
**Pull request by lberki**
Replace it with strip_import_prefix, its spiritual successor.

And apparently some automatic buildifier cleanups.

### CODE REVIEW

**Comment by johnynek** [comment]
The tests fail: ```ERROR: /home/travis/build/bazelbuild/rules_scala/test/proto/BUILD:84:1: Generating Descriptor Set proto_library //test/proto:strip_import_prefix failed (Exit 1) protoc failed: error executing command ```

**Comment by johnynek** [comment]
Maybe as simple as updating travis to use a later bazel... but we do want to keep travis green.

**Comment by johnynek** [comment]
https://github.com/bazelbuild/rules_scala/blob/master/.travis.yml see that file if you want to change it.

**Comment by lberki** [comment]
Hm, why didn't I get an e-mail about the Travis failure?

I upped the Bazel version to 0.28.1 (the newest available) in `.travis.yml`. `0.23` was ancient.

**Comment by johnynek** [comment]
travis doesn't email you unfortunately (none of the plugins for CI checking do AFAIK).

Looks like you hit a bazel deprecation now:
```
"/home/travis/.cache/bazel/_bazel_travis/7f7e07d167ded9af0372bc305ceff99e/external/io_bazel_rules_scala/scala/private/rule_impls.bzl", line 180, in compile_scala
		",".join([labels[j.path] for j in transit...])
sequence element must be a string (got 'Label'). See https://github.com/bazelbuild/bazel/issues/7802 for information about --incompatible_string_join_requires_strings.
```
shouldn't be too hard fix. Also, can you update the README to point to the current master as the last one supported by 0.23: https://github.com/bazelbuild/rules_scala#bazel-compatible-versions

PS, the last 0.23 branch was released on March 11: https://github.com/bazelbuild/bazel/releases/tag/0.23.2 to most industrial users, a 4 month old release of a project that has been out for more than 4 years, isn't "ancient". 4 years old is ancient. 2 years is pretty old. 4 months is basically HEAD. Bazel devs really need to chill out on their constant breakage. Not everyone has a full time job to chase minor API changes due to wart removal.

**Comment by lberki** [comment]
Updated `rules_impls.bzl`.

I certainly understand why churn is bad (I equally complain about code *I* depend on!), but the alternative (for now) is to live with all the current warts longer. We have been making a lot of progress in API cleanups, so churn rate should decrease significantly in the future and I hope the your experience is that it's already much better than, say, a year ago.

**Comment by dslomov** [comment]
Re "Bazel devs really need to chill out on their constant breakage" here is the plan: https://blog.bazel.build/2019/06/06/Bazel-Semantic-Versioning.html
(currently stable until Sebtember, 1.0 starting september :))

**Comment by lberki** [comment]
Meh, this *still* fails, but only under Windows which makes it hard to debug :( Is there a way for me to get the output of a test target out of Travis?

**Comment by lberki** [comment]
@iirina welp, it's not flakiness :(

**Comment by johnynek** [comment]
you might try merging master after #801 -- it might work now.

**Comment by ittaiz** [comment]
I’m not sure why the build doesn’t fail but did you see you need to replace in these places: https://github.com/bazelbuild/rules_scala/blob/44438c6205f5c4a9bf5b9b762715b88530356ea9/test_expect_failure/proto_source_root/user/BUILD

https://github.com/bazelbuild/rules_scala/blob/44438c6205f5c4a9bf5b9b762715b88530356ea9/test_expect_failure/proto_source_root/dependency/BUILD

**Comment by johnynek** [comment]
@lberki do you want to merge master and try again?

**Comment by lberki** [comment]
Sorry, I got a little overwhelmed with toil. I rebased the pull request. Let's see what Travis thinks.

**Comment by johnynek** [comment]
Looks like Travis had some flakey downloads (which I’ve been seeing a lot of lately on other projects). I’ll restart the failed jobs in the morning (8 hours from now)

**Comment by lberki** [comment]
Still fails, but it looks like it's just flakiness. Or, better said, flakiness definitely exists but some real issues might be hidden by it. Let's try again!

**Comment by lberki** [comment]
@johnynek , no need -- I just pushed a dummit commit, it's running again

**Comment by lberki** [comment]
This time it's an... OOM somehow? I'll try again, 'coz why not?

**Comment by lberki** [comment]
Okay, at least some flakiness again. I give up :S Can I merge?

**Comment by johnynek** [comment]
I'll merge when the OSX goes green. It had a download failure...

Travis really needs some kind of sha-based cache it can share and not fetch everything from the wider internet every time.

**Comment by lberki** [comment]
\o/

Thanks!

**Pull request merged**
