### PR TITLE
Update scalatest to version 3.1.2

### PR DESCRIPTION
**Pull request by cattibrie**
### Description and Motivation
Update of **scalatest** is part of the work to **update scrooge-generator to version 20.9.0**.
Issue https://github.com/bazelbuild/rules_scala/issues/1131.

Test "test_coverage_on" failed.

```
117c117
< DA:7,2
---
> DA:7,1
```

I tried to find out what DA means, but couldn't.
Is it fine to update in the `test/coverage/expected-coverage.dat` file the line 117 to be `DA:7,1`?
I run `lcov --list test/coverage/expected-coverage.dat` and it gives the same output with `DA:7,1` and `DA:7,2` in line 117.

### CODE REVIEW

**Comment by liucijus** [comment]
According to https://linux.die.net/man/1/geninfo is `DA:<line number>,<execution count>[,<checksum>]`

From what I see, coverage is also checked for the test itself, and it probably depends on ScalaTest implementation. Is this a correct coverage information I am not sure - it may also be a bug on rules side. I think it's OK to update expected coverage file for this PR.

I am planning to look into coverage related tests when I will have more time.

**Comment by liucijus** [comment]
@cattibrie please update `test/coverage/expected-coverage.dat` to pass the test

**Comment by cattibrie** [comment]
@liucijus 
Thank you for your response and pointers to geninfo. It is very helpful.

Updated the PR

**Review by liucijus — APPROVED** [review]

**Review by ittaiz — APPROVED** [review]
I hate updating the dat file but since @liucijus will tackle this across the board I think we should merge it. Thanks!

**Comment by liucijus** [comment]
> I am planning to look into coverage related tests when I will have more time.

 #1147

**Pull request merged**
