### PR TITLE
Enable local cache by default

### PR DESCRIPTION
**Pull request by andyscott**
- Enables Bazel's local cache for all development by default
- Sets up Travis to cache the local cache directory across CI builds

### CODE REVIEW

**Comment by ittaiz** [comment]
By Jenkins you mean travis?

**Comment by andyscott** [comment]
Yeah, fixed my comment already!

**Comment by johnynek** [comment]
I'm a little worried this invalidates our reproduciblity test.

We might as well remove that test if we ship this right?

**Comment by andyscott** [comment]
Where is the reproducibility test? Depending on how it's being tested, it might be possible to disabled caching for those tests.

**Comment by johnynek** [comment]
@andyscott https://github.com/bazelbuild/rules_scala/blob/master/test_rules_scala.sh#L32

**Comment by andyscott** [comment]
@johnynek:
- I split out reproducibility test into a new job
- I also disabled the cache for second round reproducibility build

**Comment by andyscott** [comment]
With caching enabled the primary job completes in about 5 minutes (as compared ~15 minutes). The new reproducibility job takes forever but the overall build time has gone down.

**Comment by johnynek** [comment]
thanks!

**Comment by ittaiz** [comment]
@johnynek thanks! I felt I was missing something...
@andyscott only problem is that people now running locally won’t run the reproducibility test. Can you add the new sh to the all.sh?

**Pull request merged**
