### PR TITLE
Scala2 12

### PR DESCRIPTION
**Pull request by or-shachar**
merged master to scala2_12

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by ittaiz** [comment]
@gkk-stripe any thoughts? Hopefully we're moving tomorrow to 2.12 so this branch will be much more important for us.
The better solution is of course to incorporate the version into the scala toolchain but we're not there yet

**Comment by gkossakowski** [comment]
Thanks for keeping this branch alive! We have one smallish repo internally that uses Scala 2.12 but it's behind on all things bazel so I can't give this PR a spin. I think keeping this branch alive until toolchain matures is ok.

The merge conflict didn't look too bad in this PR. Are you concerned with merge conflicts?

**Comment by gkossakowski** [comment]
the PR itself LGTM

**Comment by johnynek** [comment]
test this please

**Pull request merged**
